title: victus docs
description: documentation for the victus game framework
encoding: utf-8

remote_theme: sporeball/lifeblood

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

home: "/docs"

theme_color: "#0098dc"

footer_left: "made with <span class='love'>&lt;3</span> by <a href='https://sporeball.dev'>sporeball</a> &amp; <a href='https://github.com/sporeball/victus/graphs/contributors'>contributors</a>"
footer_right: "&copy; 2022"

enable_custom: true
fonts: ["Rubik:wght@300;600"]

enable_versions: true
